### ISSUE TITLE
USER STORY: Submit a poll response

### ISSUE THREAD

**Issue by MarkReddy87** [MarkReddy87/First-Agile-Projoct#3]
In order to **share my input for preferred running times, run lenghts and locations** as a **user**, I can **choose from a list of options**

## Acceptance Criteria

* The user should be able to choose options from drop down menus for run times, lenghts and locations
* The user should be able to submit thier choices to the administration

## Tasks

- [ ] Design and style the drop down menus and fill with appropriate options 
- [ ] Create and stlye the submit button 
- [ ] Test the submit button and verify it is working 

In order to **remain anonyomus** as a **user**, I can **choose to hide my username when responding to the poll**

## Acceptance Criteria

* The user should be able to submit a response anonymously 
* This should be a checkbox option located beside the submit button 

## Tasks

- [ ] Update the poll to include the checkbox beside the submit button 
- [ ] Show the name of the submitter in the poll when checkbox is unchecked 

In order to **make further suggestions** as a **user**, I can **add comments in the polling section**

## Acceptance Criteria

* The user should be able to write and submit additional comments within the poll
* The comment box should be located above the submit button at the botton of the poll

## Tasks

- [ ] Buld the comment section with a character limit of 200
- [ ] Test the comment is saved to the database location upon submitting
