### ISSUE TITLE
USER STORY: Create a poll

### ISSUE THREAD

**Issue by MarkReddy87** [MarkReddy87/First-Agile-Projoct#4]
In order to **collecte user feedback** as an **administrator**, I can **create a user poll function**

## Acceptance criteria

* The poll should appear on the homepage 
* The poll should include options for: Locations, Times and Length of runs.

## Tasks

- [ ] Decide what to include in the poll and design the layout
- [ ] Create the three different drop down menus for user selection 
- [ ] Create and style submit button 

In order to **maintain poll records** as an **administrator**, I can **save all user input / comments from current and previous polls**

## Acceptance criteria

* All user poll choices should be recorded and saved to a database
* All user comments should be saved so they can be accessed at a later date

## Tasks

- [ ] Create database for user choices 
- [ ] link submit button to database and add labels for all fields and comments section.
- [ ] Test fuctionality of the submuit button 

In order to **automatically hide the poll** as an **administrator**, I can **set a time limit for the user to respond**

## Acceptance criteria

* The poll should dissappear before midnight on the agreed date
* The user should be made aware of the time limit they have to respond
* When the poll is finished display a message advising when the next poll will start

## Tasks

- [ ] Update poll to include an expiry date 
- [ ] Create countdown timer which will be displayes to the user 
- [ ] Create message to display when the next poll will be live

**Comment by MarkReddy87** [comment]
test comment

**Comment by MarkReddy87** [comment]
In order to **maintain poll records** as an **administrator**, I can **save all user input / comments from current and previous polls**

## Acceptance criteria

*
*

## Tasks

-  [ ] 
-  [ ]

**Comment by MarkReddy87** [comment]
In order to **automatically hide the poll** as an **administrator**, I can **set a time limit for the user to respond**

## Acceptance criteria

*
*

## Tasks

-  [ ] 
-  [ ]
